name: 🐛 Bug report
description: Create a report to help us improve
title: "[Bug] "
labels: ["bug-report"]
body:
  - type: markdown
    attributes:
      value: |
        ## Setup

  - type: dropdown
    attributes:
      label: Vehicle type
      options:
        - Multicopter
        - Helicopter
        - Fixed Wing
        - Hybrid VTOL
        - Airship/Balloon
        - Rover
        - Boat
        - Submarine
        - Other

  - type: input
    attributes:
      label: Flight controller
      description: Specify your flight controller model (what type is it, where was it bought from, ...).
    validations:
      required: true

  - type: textarea
    attributes:
      label: Firmware Version
      description: |
        Which version of NextPilot are you using?
      placeholder: |
        # If you don't know the version, paste the output of `ver all` in the MAVLink Shell of QGC
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Description
        A clear and concise description of the bug and what you expected to happen.

  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of the bug.
      placeholder: |
        1. Steps to reproduce the behavior
        2. Expected behavior
        3. Add screenshot / media if you have them
    validations:
      required: true

  - type: textarea
    attributes:
      label: Flight Log Link
      description: |
        *Always* provide a link to the flight log file:
        - Download the flight log file from the vehicle ([tutorial](https://docs.px4.io/main/en/getting_started/flight_reporting.html)).
        - Upload the log to the [Flight Review](http://logs.px4.io/)
        - Share the link to the log (Copy and paste the URL of the log)
      placeholder: |
        # Paste here the link to the log
    validations:
      required: false

  - type: textarea
    attributes:
      label: Other additional context
      description: Add any other context about the problem here.
