blank_issues_enabled: false
contact_links:
  - name: Support Question
    url: https://github.com/nextpilot/nextpilot-flight-control/discussions
    about: For questions about NextPilot or related components, please use the discuss forum
  - name: Getting Started
    url: https://www.nextpilot.org/manul
    about: How to begin NextPilot, please visit user guide
  - name: Develop Center
    url: https://www.nextpilot.org/develop
    about: How to develop NextPilot, please visit develop center
