# /******************************************************************
#  *      _   __             __   ____   _  __        __
#  *     / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
#  *    /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
#  *   / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
#  *  /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
#  *
#  * Copyright All Reserved © 2015-2024 NextPilot Development Team
#  ******************************************************************/

name: build-action-test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - docs/**
      - "**/README.md"
      - "**/README_zh.md"
  pull_request:
    branches:
      - master
      - main
    paths-ignore:
      - docs/**
      - "**/README.md"
      - "**/README_zh.md"

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    name: build-sitl-qemu

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repo Code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Setup Python Tools
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup Build Tools
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install gcc gdb-multiarch -y
          sudo apt-get install gcc-arm-none-eabi binutils-arm-none-eabi -y
          sudo apt-get install qemu-system-arm -y
          # sudo apt-get install libncurses5 libncurses5-dev libncursesw5-dev -y
          python3 -m pip install -r tools/install/requirements_v3.txt

      - name: Display Tools Version
        shell: bash
        run: |
          echo "python: $(python3 -V), $(which python3)"
          echo "pip: $(pip3 -V)"
          echo "scons: $(which scons)"
          echo "$(scons --version)"
          echo "gcc: $(which arm-none-eabi-gcc)"
          echo "$(arm-none-eabi-gcc --version)"

      - name: Build bsps/silt/qemu
        shell: bash
        run: |
          export RTT_EXEC_PATH=/usr/bin/
          export RTT_CC=gcc
          scons -C bsps/sitl/qemu default -j$(nproc)
